module.exports = {
    baseURL: 'https://discordapp.com/api/v6',
    cdnURL: 'https://cdn.discordapp.com',
    events: {
        'READY': ['READY', 'ready'],
        'RESUME': ['RESUME', 'resumed'],
        'DEBUG': ['DEBUG', 'debug'],
        'MESSAGE_CREATE': ['MESSAGE_CREATE', 'message'],
        /*   */ 'MESSAGE_UPDATE': ['MESSAGE_UPDATE', 'messageUpdate'],
        /*   */ 'MESSAGE_DELETE': ['MESSAGE_DELETE', 'messageDelete'],
        /*   */ 'MESSAGE_DELETE_BULK': ['MESSAGE_DELETE_BULK', 'messageBulkDelete'],
        /*   */ 'MESSAGE_REACTION_ADD': ['MESSAGE_REACTION_ADD', 'messageReactionAdd'],
        /*   */ 'MESSAGE_REACTION_REMOVE': ['MESSAGE_REACTION_REMOVE', 'messageReactionRemove'],
        /*   */ 'MESSAGE_REACTION_REMOVE_ALL': ['MESSAGE_REACTION_REMOVE_ALL', 'messageReactionAllRemove'],
        /*   */ 'CHANNEL_CREATE': ['CHANNEL_CREATE', 'channelCreate'],
        /*   */ 'CHANNEL_UPDATE': ['CHANNEL_UPDATE', 'channelUpdate'],
        /*   */ 'CHANNEL_DELETE': ['CHANNEL_DELETE', 'channelDelete'],
        /*   */ 'CHANNEL_PINS_UPDATE': ['CHANNEL_PINS_UPDATE', 'channelPinsUpdate'],
        'GUILD_CREATE': ['GUILD_CREATE', 'guildCreate'],
        /*   */ 'GUILD_DELETE': ['GUILD_DELETE', 'guildDelete'],
        /*   */ 'GUILD_UPDATE': ['GUILD_UPDATE', 'guildUpdate'],
        'GUILD_AVAILABLE': ['GUILD_AVAILABLE', 'guildAvailable'],
        /*   */ 'GUILD_BAN_ADD': ['GUILD_BAN_ADD', 'guildBanCreate'],
        /*   */ 'GUILD_BAN_REMOVE': ['GUILD_BAN_REMOVE', 'guildBanDelete'],
        /*   */ 'GUILD_EMOJIS_UPDATE': ['GUILD_EMOJIS_UPDATE', 'guildEmojisUpdate'],
        /*   */ 'GUILD_INTEGRATIONS_UPDATE': ['GUILD_INTEGRATIONS_UPDATE', 'guildIntegrationsUpdate'],
        /*   */ 'GUILD_ROLE_CREATE': ['GUILD_ROLE_CREATE', 'roleCreate'],
        /*   */ 'GUILD_ROLE_UPDATE': ['GUILD_ROLE_UPDATE', 'roleUpdate'],
        /*   */ 'GUILD_ROLE_DELETE': ['GUILD_ROLE_DELETE', 'roleDelete'],
        /*   */ 'GUILD_MEMBER_ADD': ['GUILD_MEMBER_ADD', 'guildMemberJoin'],
        /*   */ 'GUILD_MEMBER_UPDATE': ['GUILD_MEMBER_UPDATE', 'guildMemberUpdate'],
        /*   */ 'GUILD_MEMBER_REMOVE': ['GUILD_MEMBER_REMOVE', 'guildMemberLeave'],
        /*   */ 'GUILD_MEMBER_CHUNK': ['GUILD_MEMBER_CHUNK', 'guildMemberChunk'],
        /*   */ 'PRESENCE_UPDATE': ['PRESENCE_UPDATE', 'presenceUpdate'],
        /*   */ 'VOICE_STATE_UPDATE': ['VOICE_STATE_UPDATE', 'voiceStateUpdate'],
        /*   */ 'VOICE_SERVER_UPDATE': ['VOICE_SERVER_UPDATE', 'voiceServerUpdate'],
        /*   */ 'WEBHOOKS_UPDATE': ['WEBHOOKS_UPDATE', 'webhookUpdate'],
        /*   */ 'INVITE_CREATE': ['INVITE_CREATE', 'inviteCreate'],
        /*   */ 'INVITE_DELETE': ['INVITE_DELETE', 'inviteDelete'],
        /*   */ 'USER_UPDATE': ['USER_UPDATE', 'userUpdate'],
        /*   */ 'TYPING_START': ['TYPING_START', 'userTypingStart'],
    },
    opcodes: {
        DISPATCH: 0,
        HEARTBEAT: 1,
        IDENTIFY: 2,
        STATUS_UPDATE: 3,
        VOICE_STATE_UPDATE: 4,
        VOICE_SERVER_PING: 5,
        RESUME: 6,
        RECONNECT: 7,
        REQUEST_GUILD_MEMBERS: 8,
        INVALID_SESSION: 9,
        HELLO: 10,
        HEARTBEAT_ACK: 11
    },
    channelTypes: {
        TEXT: 0,
        DM: 1,
        VOICE: 2,
        GROUP_DM: 3,
        CATEGORY: 4,
        NEWS: 5,
        STORE: 6
    }
}