module.exports = {
    baseURL: 'https://discordapp.com/api/v6',
    cdnURL: 'https://cdn.discordapp.com',
    events: {
        READY: ['READY', 'ready'],
        RESUME: ['RESUME', 'resumed'],
        DEBUG: ['DEBUG', 'debug'],
        MESSAGE_CREATE: ['MESSAGE_CREATE', 'message'],
        /*   */ 'MESSAGE_UPDATE': ['MESSAGE_UPDATE', 'messageUpdate'],
        /*   */ 'MESSAGE_DELETE': ['MESSAGE_DELETE', 'messageDelete'],
        /*   */ 'MESSAGE_DELETE_BULK': ['MESSAGE_DELETE_BULK', 'messageBulkDelete'],
        /*   */ 'MESSAGE_REACTION_ADD': ['MESSAGE_REACTION_ADD', 'messageReactionAdd'],
        /*   */ 'MESSAGE_REACTION_REMOVE': ['MESSAGE_REACTION_REMOVE', 'messageReactionRemove'],
        /*   */ 'MESSAGE_REACTION_REMOVE_ALL': ['MESSAGE_REACTION_REMOVE_ALL', 'messageReactionAllRemove'],
        /*   */ 'CHANNEL_CREATE': ['CHANNEL_CREATE', 'channelCreate'],
        /*   */ 'CHANNEL_UPDATE': ['CHANNEL_UPDATE', 'channelUpdate'],
        /*   */ 'CHANNEL_DELETE': ['CHANNEL_DELETE', 'channelDelete'],
        /*   */ 'CHANNEL_PINS_UPDATE': ['CHANNEL_PINS_UPDATE', 'channelPinsUpdate'],
        GUILD_CREATE: ['GUILD_CREATE', 'guildCreate'],
        GUILD_DELETE: ['GUILD_DELETE', 'guildDelete'],
        GUILD_UPDATE: ['GUILD_UPDATE', 'guildUpdate'],
        GUILD_AVAILABLE: ['GUILD_AVAILABLE', 'guildAvailable'],
        /*   */ 'GUILD_BAN_ADD': ['GUILD_BAN_ADD', 'guildBanCreate'],
        /*   */ 'GUILD_BAN_REMOVE': ['GUILD_BAN_REMOVE', 'guildBanDelete'],
        /*   */ 'GUILD_EMOJIS_UPDATE': ['GUILD_EMOJIS_UPDATE', 'guildEmojisUpdate'],
        /*   */ 'GUILD_INTEGRATIONS_UPDATE': ['GUILD_INTEGRATIONS_UPDATE', 'guildIntegrationsUpdate'],
        /*   */ 'GUILD_ROLE_CREATE': ['GUILD_ROLE_CREATE', 'roleCreate'],
        /*   */ 'GUILD_ROLE_UPDATE': ['GUILD_ROLE_UPDATE', 'roleUpdate'],
        /*   */ 'GUILD_ROLE_DELETE': ['GUILD_ROLE_DELETE', 'roleDelete'],
        /*   */ 'GUILD_MEMBER_ADD': ['GUILD_MEMBER_ADD', 'guildMemberJoin'],
        /*   */ 'GUILD_MEMBER_UPDATE': ['GUILD_MEMBER_UPDATE', 'guildMemberUpdate'],
        /*   */ 'GUILD_MEMBER_REMOVE': ['GUILD_MEMBER_REMOVE', 'guildMemberLeave'],
        /*   */ 'GUILD_MEMBER_CHUNK': ['GUILD_MEMBER_CHUNK', 'guildMemberChunk'],
        /*   */ 'PRESENCE_UPDATE': ['PRESENCE_UPDATE', 'presenceUpdate'],
        /*   */ 'VOICE_STATE_UPDATE': ['VOICE_STATE_UPDATE', 'voiceStateUpdate'],
        /*   */ 'VOICE_SERVER_UPDATE': ['VOICE_SERVER_UPDATE', 'voiceServerUpdate'],
        /*   */ 'WEBHOOKS_UPDATE': ['WEBHOOKS_UPDATE', 'webhookUpdate'],
        /*   */ 'INVITE_CREATE': ['INVITE_CREATE', 'inviteCreate'],
        /*   */ 'INVITE_DELETE': ['INVITE_DELETE', 'inviteDelete'],
        /*   */ 'USER_UPDATE': ['USER_UPDATE', 'userUpdate'],
        /*   */ 'TYPING_START': ['TYPING_START', 'typing'],
    },
    opcodes: {
        DISPATCH: 0,
        HEARTBEAT: 1,
        IDENTIFY: 2,
        STATUS_UPDATE: 3,
        VOICE_STATE_UPDATE: 4,
        VOICE_SERVER_PING: 5,
        RESUME: 6,
        RECONNECT: 7,
        REQUEST_GUILD_MEMBERS: 8,
        INVALID_SESSION: 9,
        HELLO: 10,
        HEARTBEAT_ACK: 11
    },
    channelTypes: {
        TEXT: 0,
        DM: 1,
        VOICE: 2,
        GROUP_DM: 3,
        CATEGORY: 4,
        NEWS: 5,
        STORE: 6
    },
    permissions: {
        CREATE_INSTANT_INVITE: { hex: 0x00000001, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT, this.channelTypes.VOICE] },
        KICK_MEMBERS: { hex: 0x00000002, twofactor: true, overrides: [], channelTypes: [] },
        BAN_MEMBERS: { hex: 0x00000004, twofactor: true, overrides: [], channelTypes: [] },
        ADMINISTRATOR: { hex: 0x00000008, twofactor: true, overrides: true, channelTypes: [] },
        MANAGE_CHANNELS: { hex: 0x00000010, twofactor: true, overrides: [], channelTypes: [this.channelTypes.TEXT, this.channelTypes.VOICE] },
        MANAGE_GUILD: { hex: 0x00000020, twofactor: true, overrides: [], channelTypes: [] },
        ADD_REACTIONS: { hex: 0x00000040, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        VIEW_AUDIT_LOG: { hex: 0x00000080, twofactor: false, overrides: [], channelTypes: [] },
        PRIORITY_SPEAKER: { hex: 0x00000100, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        STREAM: { hex: 0x00000200, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        VIEW_CHANNEL: { hex: 0x00000400, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT, this.channelTypes.VOICE] },
        SEND_MESSAGES: { hex: 0x00000800, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        SEND_TTS_MESSAGES: { hex: 0x00001000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        MANAGE_MESSAGES: { hex: 0x00002000, twofactor: true, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        EMBED_LINKS: { hex: 0x00004000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        ATTACH_FILES: { hex: 0x00008000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        READ_MESSAGE_HISTORY: { hex: 0x00010000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        MENTION_EVERYONE: { hex: 0x00020000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        USE_EXTERNAL_EMOJIS: { hex: 0x00040000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.TEXT] },
        VIEW_GUILD_INSIGHTS	: { hex: 0x00080000, twofactor: false, overrides: [], channelTypes: [] },
        CONNECT: { hex: 0x00100000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        SPEAK: { hex: 0x00200000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        MUTE_MEMBERS: { hex: 0x00400000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        DEAFEN_MEMBERS: { hex: 0x00800000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        MOVE_MEMBERS: { hex: 0x01000000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        USE_VAD: { hex: 0x02000000, twofactor: false, overrides: [], channelTypes: [this.channelTypes.VOICE] },
        CHANGE_NICKNAME: { hex: 0x04000000, twofactor: false, overrides: [], channelTypes: [] },
        MANAGE_NICKNAMES: { hex: 0x08000000, twofactor: false, overrides: [], channelTypes: [] },
        MANAGE_ROLES: { hex: 0x10000000, twofactor: true, overrides: [], channelTypes: [this.channelTypes.TEXT, this.channelTypes.VOICE] },
        MANAGE_WEBHOOKS: { hex: 0x20000000, twofactor: true, overrides: [], channelTypes: [this.channelTypes.TEXT, this.channelTypes.VOICE] },
        MANAGE_EMOJIS: { hex: 0x40000000, twofactor: true, overrides: [], channelTypes: [] }
    }
}